### ISSUE TITLE
Scaling Issue

### ISSUE THREAD

**Issue by khadiravana-belagavi** [doc-analysis/DocBank#29]
Using the data points given for the docBank dataset on pdf files, we are getting a very distorted annotation on overlaying the data-points on images -- resized to the pdf height and width. We used the normalization to 1000 procedure that you have suggested in other issue. However the following is an example of the distorted output:

![docBank_problem](https://user-images.githubusercontent.com/57064909/119567639-2cf18000-bdca-11eb-8f0a-99c8dd3abd5a.jpeg)

**Comment by PranavTadimeti** [comment]
So I think I know what your issue might be.

In https://github.com/doc-analysis/DocBank/blob/b765d7afc403acb5aab7c1727440029466510a90/scripts/pdf_process.py#L89, there are 2 steps for normalization: one is ensuring the range of the coordinates are within that of the image dimensions, and making it 1000 if so. The other step reverses this to get the final normalized points. However, the coordinates being stored is only after step 1, so you would need to do https://github.com/doc-analysis/DocBank/blob/b765d7afc403acb5aab7c1727440029466510a90/scripts/pdf_process.py#L97 in order to correctly plot the bounding boxes.

**Comment by khadiravana-belagavi** [comment]
thanks @PranavTadimeti ! Works Fine now!
